/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GameRouteImport } from './routes/game'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameIdRouteImport } from './routes/game.$id'
import { Route as GameIdIndexRouteImport } from './routes/game.$id.$index'

const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIdRoute = GameIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GameRoute,
} as any)
const GameIdIndexRoute = GameIdIndexRouteImport.update({
  id: '/$index',
  path: '/$index',
  getParentRoute: () => GameIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game': typeof GameRouteWithChildren
  '/game/$id': typeof GameIdRouteWithChildren
  '/game/$id/$index': typeof GameIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game': typeof GameRouteWithChildren
  '/game/$id': typeof GameIdRouteWithChildren
  '/game/$id/$index': typeof GameIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/game': typeof GameRouteWithChildren
  '/game/$id': typeof GameIdRouteWithChildren
  '/game/$id/$index': typeof GameIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/game' | '/game/$id' | '/game/$id/$index'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/game' | '/game/$id' | '/game/$id/$index'
  id: '__root__' | '/' | '/game' | '/game/$id' | '/game/$id/$index'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameRoute: typeof GameRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$id': {
      id: '/game/$id'
      path: '/$id'
      fullPath: '/game/$id'
      preLoaderRoute: typeof GameIdRouteImport
      parentRoute: typeof GameRoute
    }
    '/game/$id/$index': {
      id: '/game/$id/$index'
      path: '/$index'
      fullPath: '/game/$id/$index'
      preLoaderRoute: typeof GameIdIndexRouteImport
      parentRoute: typeof GameIdRoute
    }
  }
}

interface GameIdRouteChildren {
  GameIdIndexRoute: typeof GameIdIndexRoute
}

const GameIdRouteChildren: GameIdRouteChildren = {
  GameIdIndexRoute: GameIdIndexRoute,
}

const GameIdRouteWithChildren =
  GameIdRoute._addFileChildren(GameIdRouteChildren)

interface GameRouteChildren {
  GameIdRoute: typeof GameIdRouteWithChildren
}

const GameRouteChildren: GameRouteChildren = {
  GameIdRoute: GameIdRouteWithChildren,
}

const GameRouteWithChildren = GameRoute._addFileChildren(GameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameRoute: GameRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
